<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHH9T8uS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHH9T8uS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHH9T8uS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHH9T8uS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHH9T8uS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HH9T8uS',
    'container.build_id' => 'eaa9b919',
    'container.build_time' => 1601833216,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHH9T8uS');
